### ISSUE TITLE
Combining Shamir’s Secret Sharing 2-out-of-3 does not work on Android app

### ISSUE THREAD

**Issue by tychsen** [mycelium-com/wallet-android#574]
Reproduce:

1) Press Add New Account
2) Press Advanced
3) Press Scan
4) Scan share 1
5) Scan share 2
6) After some loading time the app goes back to Add New Account page - the address is not in the list of wallets.

**Comment by Giszmo** [comment]
This issue should be fixed in 3.8.9.0, available on Google Play.

**Comment by tychsen** [comment]
Hi,

Running 3.8.9.1 - problem persists. Please reopen ticket.

**Comment by Giszmo** [comment]
done. Was the SSS key created by Mycelium? I guess we need more details.

**Comment by tychsen** [comment]
Sending over some keys...

**Comment by Giszmo** [comment]
Issue can be reproduced. We will fix it asap.
